[metadata]
name = gd-qpt
version = 0.0.1

[options]
python_requires = >=3.8,<3.9
package_dir =
    =src
packages =
    gd_qpt
install_requires =
    numpy==1.21.6
    scipy==1.7.3
    matplotlib==3.5.3
    qutip==4.7.0
    cvxpy==1.2.3
    scs==3.0.0
    dm-haiku==0.0.9
    optax==0.1.4
    tqdm>=4.0
    jax<0.5
    jaxlib<0.5